# Generated by Django 6.1.1 on 2026-09-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementcentre',
            name='num_counters',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
