# Generated by Django 6.1.1 on 2026-09-24 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_procurementcentre_num_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(choices=[('weather_disaster', 'Weather / Disaster'), ('health_emergency', 'Health Emergency'), ('other', 'Other')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='core.booking')),
                ('previous_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.slot')),
                ('target_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests', to='core.slot')),
            ],
        ),
    ]
